import type { L } from '@/lib/i18n';

const l = (en: string, ar: string): L => ({ en, ar });

/** All editorial copy. English follows the Figma / FigJam source wording; Arabic should be reviewed by a native editor before launch. */
export const COPY = {
  site: {
    title: l('AQARATI — Brand Experience', 'عقاراتي — تجربة الهوية'),
    skip: l('Skip to content', 'تخطَّ إلى المحتوى'),
    tagline: l('Your property journey', 'رحلتك العقارية'),
  },

  ui: {
    explore: l('Explore', 'استكشف'),
    scroll: l('Scroll to explore', 'مرّر للاستكشاف'),
    menu: l('Chapters', 'الفصول'),
    openMenu: l('Open chapters', 'افتح الفصول'),
    closeMenu: l('Collapse navigation', 'اطوِ التنقل'),
    theme: l('Theme', 'المظهر'),
    toLight: l('Switch to light theme', 'التبديل إلى المظهر الفاتح'),
    toDark: l('Switch to dark theme', 'التبديل إلى المظهر الداكن'),
    language: l('Language', 'اللغة'),
    toArabic: l('Switch to Arabic', 'التبديل إلى العربية'),
    toEnglish: l('Switch to English', 'التبديل إلى الإنجليزية'),
    close: l('Close', 'إغلاق'),
    prev: l('Previous', 'السابق'),
    next: l('Next', 'التالي'),
    measured: l('Measured from artwork', 'مقاس من العمل الفني'),
    proposed: l('Proposed · requires brand approval', 'مقترح · يتطلب اعتماد العلامة'),
    sample: l('Sample content', 'محتوى تجريبي'),
    source: l('Source', 'المصدر'),
    chapter: l('Chapter', 'الفصل'),
    correct: l('Correct', 'صحيح'),
    incorrect: l('Incorrect', 'غير صحيح'),
    light: l('Light', 'فاتح'),
    dark: l('Dark', 'داكن'),
    english: l('English', 'الإنجليزية'),
    arabic: l('Arabic', 'العربية'),
    display: l('Display', 'العناوين'),
    body: l('Body', 'النص'),
    copy: l('Copied', 'تم النسخ'),
    zoom: l('Open plate', 'افتح اللوحة'),
    credits: l('Photo credits', 'حقوق الصور'),
    creditsNote: l('Wikimedia Commons photographs, licensed and cropped for reference. No endorsement or property-listing claim.', 'صور من ويكيميديا كومنز بتراخيص مفتوحة ومقتطعة للمرجعية. لا تأييد ولا ادعاء بعرض عقاري.'),
  },

  hero: {
    eyebrow: l('Brand experience', 'تجربة الهوية'),
    line1: l('Trusted by design.', 'موثوقة بالتصميم.'),
    line2: l('Defined by place.', 'محددة بالمكان.'),
    sub: l('The identity, visual language and digital expression of AQARATI, Oman’s trusted property ecosystem.', 'الهوية واللغة البصرية والتعبير الرقمي لعقاراتي، منظومة العقار الموثوقة في عُمان.'),
    measure: l('Master vector · 440 × 484', 'الملف المعتمد · 440 × 484'),
  },

  essence: {
    num: '01',
    title: l('Brand essence', 'جوهر العلامة'),
    words: [l('Trust', 'الثقة'), l('Place', 'المكان'), l('Journey', 'الرحلة')],
    lead: l('Trust before participation. Every interaction answers five questions before the user proceeds.', 'الثقة قبل المشاركة. كل تفاعل يجيب عن خمسة أسئلة قبل أن يتابع المستخدم.'),
    questions: [l('What am I looking at?', 'ماذا أرى؟'), l('Who is behind it?', 'من يقف خلفه؟'), l('Has it been verified?', 'هل تم التحقق منه؟'), l('What can I do?', 'ماذا يمكنني أن أفعل؟'), l('What happens next?', 'ماذا يحدث بعد ذلك؟')],
    pillars: [
      { t: l('Architecture', 'العمارة'), d: l('The identity draws from premium architecture, editorial publishing and quiet luxury, rather than generic real-estate or SaaS conventions.', 'تستلهم الهوية العمارة الراقية والنشر التحريري والفخامة الهادئة، لا الأعراف العقارية أو الرقمية الشائعة.') },
      { t: l('Heritage', 'الإرث'), d: l('Rooted in Oman. A mocha drawn from the master artwork, an ivory field like plaster, a wave that meets the roofline.', 'متجذّرة في عُمان. موكا مأخوذ من الشعار، وعاجي كالجص، وموجة تلتقي بخط السقف.') },
      { t: l('Human connection', 'التواصل الإنساني'), d: l('Verification is human and deliberate. A verified email never means an approved business role.', 'التوثيق إنساني ومدروس. البريد الموثّق لا يعني دوراً تجارياً معتمداً.') },
    ],
    caption: l('Architecture / honest arrival', 'عمارة / مدخل صادق'),
  },

  identity: {
    num: '02',
    title: l('Identity', 'الهوية'),
    lead: l('One master logo. A house that meets a wave, an Arabic and a Latin wordmark, and the line “Your property journey”. It is never redrawn, only protected.', 'شعار رئيسي واحد. بيت يلتقي بموجة، وكلمة عربية وأخرى لاتينية، وعبارة «رحلتك العقارية». لا يُعاد رسمه، بل يُحمى.'),
    masterLabel: l('Approved vector master', 'الملف المعتمد'),
    masterNote: l('The master AQARATI logo must remain unchanged. All variations, app-icon adaptations and production exports are derived from the master artwork.', 'يجب أن يبقى الشعار الرئيسي دون تغيير. كل النسخ وتعديلات أيقونة التطبيق والمخرجات مشتقة منه.'),
    parts: [
      { n: '01', t: l('Symbol', 'الرمز'), d: l('House and wave', 'البيت والموجة') },
      { n: '02', t: l('Arabic wordmark', 'الكلمة العربية'), d: l('عقاراتي', 'عقاراتي') },
      { n: '03', t: l('English wordmark', 'الكلمة الإنجليزية'), d: l('AQARATI', 'AQARATI') },
      { n: '04', t: l('Tagline', 'العبارة'), d: l('Your property journey', 'رحلتك العقارية') },
    ],
    studiesTitle: l('The anatomy, plate by plate', 'التشريح، لوحة بلوحة'),
    variantsTitle: l('Variants', 'النسخ'),
    variantsLead: l('Choose a variant. Each is derived from the unchanged master.', 'اختر نسخة. كلها مشتقة من الملف الرئيسي دون تغيير.'),
    sizeTitle: l('How small can it go?', 'إلى أي حد يمكن تصغيره؟'),
    sizeLead: l('Drag to shrink the intact master. These are visual observations; the Figma file records no locked minimum yet.', 'اسحب لتصغير الشعار الكامل. هذه ملاحظات بصرية، ولا يوجد حد أدنى معتمد في ملف التصميم بعد.'),
    sizeNote: l('Observation only. Final minimum size to be locked after brand review.', 'ملاحظة فقط. يُحدد الحد الأدنى النهائي بعد مراجعة العلامة.'),
    sizeLabel: l('Container height', 'ارتفاع الحاوية'),
    clearTitle: l('Clear space', 'المساحة الآمنة'),
    clearBody: l('X is the height of the first Latin capital A in AQARATI. The proposed protected area is X on all sides; nothing enters it.', 'X هو ارتفاع أول حرف A لاتيني في AQARATI. المساحة المحمية المقترحة X من كل جانب ولا يدخلها شيء.'),
    clearHover: l('Hover to reveal the protected boundary', 'مرّر لإظهار الحدود المحمية'),
    tones: {
      primary: l('Primary', 'الأساسي'),
      symbol: l('Symbol', 'الرمز'),
      mono: l('Monochrome', 'أحادي'),
      reverse: l('Reverse', 'معكوس'),
      compact: l('Compact', 'مدمج'),
      horizontal: l('Horizontal', 'أفقي'),
      stacked: l('Stacked', 'عمودي'),
    },
    toneNote: {
      primary: l('Full lockup. Symbol, Arabic and Latin wordmarks, tagline.', 'التركيب الكامل: الرمز والكلمتان والعبارة.'),
      symbol: l('Very compact identification. The house and wave only.', 'تعريف مضغوط جداً: البيت والموجة فقط.'),
      mono: l('Single-colour reproduction.', 'استنساخ بلون واحد.'),
      reverse: l('Warm ivory contours on the deep warm neutral.', 'خطوط عاجية دافئة على حيادي دافئ داكن.'),
      compact: l('Tagline and dividers removed, for compact placements.', 'دون العبارة والفواصل للمساحات الصغيرة.'),
      horizontal: l('Symbol beside the wordmarks, for wide headers.', 'الرمز بجانب الكلمتين للترويسات العريضة.'),
      stacked: l('Centred vertical presentation.', 'عرض عمودي متمركز.'),
    },
  },

  typography: {
    num: '03',
    title: l('Typography', 'الخطوط'),
    lead: l('Two voices, one system. Fraunces gives an editorial voice; Plus Jakarta Sans keeps navigation, forms, body and data direct.', 'صوتان في منظومة واحدة. تمنح Fraunces نبرة تحريرية، وتُبقي Plus Jakarta Sans التنقل والنماذج والنص والبيانات مباشرة.'),
    display: l('Display', 'العناوين'),
    displayNote: l('Fraunces · editorial titles, hero statements, large numbers', 'Fraunces · عناوين تحريرية وعبارات رئيسية وأرقام كبيرة'),
    bodyNote: l('Plus Jakarta Sans · body, labels, navigation, buttons', 'Plus Jakarta Sans · النص والعناوين الفرعية والتنقل والأزرار'),
    arabicNote: l('IBM Plex Sans Arabic · all Arabic and RTL content', 'IBM Plex Sans Arabic · كل المحتوى العربي والكتابة من اليمين'),
    specimenTitle: l('A place to belong.', 'مكان تنتمي إليه.'),
    scaleTitle: l('The scale', 'السلّم'),
    scaleLead: l('Twelve native roles with explicit size, line height, weight and family. Sizes below are the desktop values.', 'اثنا عشر دوراً بحجم وارتفاع سطر ووزن وعائلة محددة. الأحجام أدناه هي قيم سطح المكتب.'),
    arabicTitle: l('Arabic, equally considered', 'العربية بالعناية نفسها'),
    arabicLead: l('Right-aligned labels, mirrored layouts, Arabic numerals and OMR formats are designed together, never retrofitted.', 'تُصمَّم العناوين اليمينية والتخطيطات المعكوسة والأرقام العربية وصيغ الريال العُماني معاً، لا لاحقاً.'),
    arabicHeadline: l('عقارك يبدأ من هنا', 'عقارك يبدأ من هنا'),
    arabicBody: l('ابحث عن عقارك في مسقط. اختر الموقع ونوع العقار، ثم راجع التفاصيل وحدد موعداً للمعاينة.', 'ابحث عن عقارك في مسقط. اختر الموقع ونوع العقار، ثم راجع التفاصيل وحدد موعداً للمعاينة.'),
    arabicCaption: l('عقار تجريبي — ليس عرضاً فعلياً', 'عقار تجريبي — ليس عرضاً فعلياً'),
    arabicStatus: l('The Arabic typeface is still marked pending decision in Figma. IBM Plex Sans Arabic is used here.', 'لا يزال الخط العربي «قيد القرار» في ملف التصميم. يُستخدم هنا IBM Plex Sans Arabic.'),
    numerals: l('Numbers and currency', 'الأرقام والعملة'),
    controls: { language: l('Language', 'اللغة'), role: l('Voice', 'النبرة') },
    price: l('OMR 185,000', '١٨٥٬٠٠٠ ر.ع.'),
    beds: l('4 Beds', '٤ غرف'),
    placeline: l('Al Mouj, Muscat', 'الموج، مسقط'),
  },

  colour: {
    num: '04',
    title: l('Colour', 'الألوان'),
    lead: l('Stone, paper, wood and plaster. A grounded, warm identity: do not turn every surface brown.', 'حجر وورق وخشب وجص. هوية دافئة ومتماسكة: لا تجعل كل سطح بنياً.'),
    brand: l('Brand colours', 'ألوان العلامة'),
    brandNote: l('Measured from the master artwork.', 'مقاسة من الشعار الرئيسي.'),
    ui: l('UI colours', 'ألوان الواجهة'),
    uiNote: l('Supporting neutrals. Proposed.', 'محايدات داعمة. مقترحة.'),
    semantic: l('Semantic colours', 'الألوان الدلالية'),
    semanticNote: l('Meaning is carried by text and icon as well as colour. Proposed.', 'المعنى يُحمل بالنص والأيقونة وليس باللون وحده. مقترحة.'),
    proportions: l('Proportion', 'النسب'),
    hint: l('Select a colour', 'اختر لوناً'),
    copyHex: l('Copy HEX', 'انسخ HEX'),
    tokensTitle: l('Light and dark, designed together', 'الفاتح والداكن، بتصميم مشترك'),
    tokensLead: l('Dark mode is not an inversion. Deep warm neutral surfaces, warm ivory text, mocha as a fill.', 'الوضع الداكن ليس قلباً للألوان. أسطح دافئة داكنة ونص عاجي ودرجة الموكا كتعبئة.'),
    role: l('Role', 'الدور'),
    contrastLabel: l('Contrast on', 'التباين على'),
  },

  visual: {
    num: '05',
    title: l('Visual language', 'اللغة البصرية'),
    lead: l('Large negative space. Thin structural lines over heavy borders. Surface contrast before shadows. Pills only for status.', 'مساحات سالبة واسعة. خطوط بنيوية رفيعة بدل الحدود الثقيلة. تباين الأسطح قبل الظلال. الأشكال الحبيّة للحالات فقط.'),
    photoTitle: l('Photography', 'التصوير'),
    photoLead: l('Places, not promises. Calm, authentic, premium: how a place feels to inhabit.', 'أماكن لا وعود. هادئ وأصيل وراقٍ: كيف يبدو المكان حين تسكنه.'),
    iconTitle: l('Iconography', 'الأيقونات'),
    iconLead: l('One editable outline family on a 24-unit viewport, for interface meaning. Not an extension of the brand symbol.', 'عائلة خطية واحدة على إطار 24 وحدة لمعنى الواجهة. ليست امتداداً لرمز العلامة.'),
    iconSpec: [
      { k: l('Viewport', 'الإطار'), v: '24 × 24' },
      { k: l('Stroke', 'السماكة'), v: '1.75 px' },
      { k: l('Sizes', 'الأحجام'), v: '16 · 20 · 24 · 28 · 32' },
    ],
    iconStatus: l('Proposed outline family, exploratory 1.75 px baseline.', 'عائلة خطية مقترحة بخط أساس 1.75 px.'),
    illusTitle: l('Illustration', 'الرسوم'),
    illusLead: l('Editable architectural geometry and restrained empty-state concepts. Not cartoons, not inventory.', 'هندسة معمارية قابلة للتحرير وحالات فارغة هادئة. لا كاريكاتير ولا مخزون.'),
    spacingTitle: l('Spacing', 'المسافات'),
    spacingNum: '06',
    spacingLead: l('A 4 px base and eleven native tokens, applied to real grouping and reading rhythm.', 'وحدة أساس 4 px وإحدى عشرة قيمة، تُطبق على التجميع الفعلي وإيقاع القراءة.'),
    spacingHover: l('Hover a step to measure it', 'مرّر على خطوة لقياسها'),
    radiusTitle: l('Form and surface', 'الشكل والسطح'),
    radiusNum: '07',
    radiusLead: l('A restrained hierarchy from sharp architecture to softened interactive containers. Not every element is a pill.', 'تسلسل هادئ من العمارة الحادة إلى حاويات تفاعلية ناعمة. ليس كل عنصر حبّة.'),
    elevTitle: l('Elevation', 'الارتفاع'),
    elevLead: l('Surface contrast before shadow. Shadows stay subtle and are reserved for what floats.', 'تباين الأسطح قبل الظل. تبقى الظلال خفيفة ومخصصة لما يطفو.'),
    motionTitle: l('Motion', 'الحركة'),
    motionNum: '08',
    motionLead: l('Subtle, fluid, restrained. Calm arrivals, controlled departures, no decorative overshoot.', 'خفيفة وسلسة وهادئة. ظهور ساكن وخروج منضبط ودون ارتداد زخرفي.'),
    play: l('Play', 'شغّل'),
    replay: l('Replay', 'أعد التشغيل'),
    reduced: l('Reduced motion', 'تقليل الحركة'),
    reducedNote: l('When the system asks for reduced motion, movement is removed and state changes remain.', 'عند طلب النظام تقليل الحركة تُزال الحركة وتبقى تغييرات الحالة.'),
    demoTitles: {
      reveal: l('Reveal', 'ظهور'),
      selection: l('Selection', 'اختيار'),
      sheet: l('Sheet', 'ورقة سفلية'),
      loading: l('Loading', 'تحميل'),
      success: l('Success', 'نجاح'),
      error: l('Error', 'خطأ'),
    },
    sheetTitle: l('Viewing request', 'طلب معاينة'),
    sheetBody: l('Send a viewing request for this property. Availability is confirmed separately.', 'أرسل طلب معاينة لهذا العقار. يتم تأكيد التوفر بشكل منفصل.'),
    submitted: l('Viewing request submitted', 'تم إرسال طلب المعاينة'),
    submittedNote: l('Your request has been recorded.', 'تم تسجيل طلبك.'),
    errorTitle: l('Something needs attention', 'هناك ما يحتاج إلى انتباه'),
    errorNote: l('Check the highlighted field and try again.', 'تحقق من الحقل المحدد وحاول مجدداً.'),
    selectA: l('Villa', 'فيلا'),
    selectB: l('Apartment', 'شقة'),
    selectC: l('Land', 'أرض'),
    openSheet: l('Book a viewing', 'احجز معاينة'),
    confirm: l('Confirm request', 'أكّد الطلب'),
  },

  product: {
    num: '09',
    title: l('Product expression', 'التعبير في المنتج'),
    lead: l('Where the identity enters the product. The same warmth, hierarchy and restraint, on real screens.', 'حيث تدخل الهوية المنتج. الدفء والتسلسل والهدوء نفسها، على شاشات حقيقية.'),
    lightTitle: l('Light experience', 'التجربة الفاتحة'),
    lightLead: l('Warm neutral surfaces, editorial typography and restrained brand colour. Verification is communicated as a product state, not a decorative promise.', 'أسطح محايدة دافئة وطباعة تحريرية ولون علامة هادئ. يُعرض التوثيق كحالة في المنتج لا كوعد زخرفي.'),
    darkTitle: l('Dark experience', 'التجربة الداكنة'),
    darkLead: l('Deep warm neutral, warm ivory text, mocha as a fill. A theme designed, not inverted.', 'حيادي دافئ داكن ونص عاجي والموكا كتعبئة. مظهر مُصمَّم لا مقلوب.'),
    navTitle: l('One persistent destination system', 'منظومة وجهات ثابتة'),
    navLead: l('Four destinations, exactly: Home, Explore, Activity and Account. The active state is explicit, never colour alone.', 'أربع وجهات بالضبط: الرئيسية واستكشف والنشاط والحساب. الحالة النشطة واضحة وليست باللون وحده.'),
    productNav: [l('Home', 'الرئيسية'), l('Explore', 'استكشف'), l('Activity', 'النشاط'), l('Account', 'الحساب')],
    propertyTitle: l('A property, expressed', 'عقار، كما يُعبَّر عنه'),
    propertyLead: l('Title establishes the property, location supports it, price remains explicit. The photograph is an architectural reference, not listing evidence.', 'العنوان يعرّف العقار، والموقع يدعمه، والسعر يبقى صريحاً. الصورة مرجع معماري وليست دليلاً على عرض.'),
    propertyTag: l('Verified property', 'عقار موثّق'),
    propertyName: l('4-Bedroom Contemporary Villa', 'فيلا عصرية من 4 غرف'),
    propertyLoc: l('Al Mouj, Muscat', 'الموج، مسقط'),
    propertyPrice: l('OMR 285,000', '٢٨٥٬٠٠٠ ر.ع.'),
    propertyFacts: l('4 Beds · 5 Baths · 420 m²', '٤ غرف · ٥ حمامات · ٤٢٠ م²'),
    propertyCta: l('Request a viewing', 'اطلب معاينة'),
    propertyNote: l('Sample property information. Not actual inventory.', 'معلومات عقار تجريبية. ليست مخزوناً فعلياً.'),
    verifTitle: l('Verification, quietly', 'التوثيق بهدوء'),
    verifLead: l('Authentication asks “Who are you?”. Verification asks “Has AQARATI approved you?”. They are never visually merged. States are human and deliberate, carried by text and icon as well as colour.', 'المصادقة تسأل «من أنت؟». والتوثيق يسأل «هل اعتمدتك عقاراتي؟». لا يُدمجان بصرياً. الحالات إنسانية ومدروسة وتُحمل بالنص والأيقونة وليس باللون وحده.'),
    journeyTitle: l('The journey', 'الرحلة'),
    journeyLead: l('Every user moves through one ecosystem, connected by trust.', 'كل مستخدم يتحرك في منظومة واحدة تربطها الثقة.'),
    viewingTitle: l('Viewing', 'المعاينة'),
    maintenanceTitle: l('Maintenance', 'الصيانة'),
    flowNote: l('Reviews are possible only after an eligible completed interaction: a viewing or maintenance completion.', 'التقييم متاح فقط بعد تفاعل مكتمل مؤهل: معاينة أو إتمام صيانة.'),
    roles: l('Six public sign-up paths, one ecosystem', 'ستة مسارات تسجيل عامة، منظومة واحدة'),
    rolesList: [l('User to Shop', 'مستخدم للتسوق'), l('Real estate agent', 'وكيل عقاري'), l('Construction company', 'شركة إنشاءات'), l('Property development company', 'شركة تطوير عقاري'), l('Building architecture', 'عمارة المباني'), l('Interior & exterior design', 'تصميم داخلي وخارجي')],
  },

  applications: {
    num: '10',
    title: l('Applications', 'التطبيقات'),
    lead: l('The identity beyond a single screen: icon, launch and the surfaces around the product.', 'الهوية خارج الشاشة الواحدة: الأيقونة والإطلاق والأسطح المحيطة بالمنتج.'),
    iconTitle: l('App icon', 'أيقونة التطبيق'),
    iconLead: l('The symbol is the icon. Warm ivory, original two-tone mocha, 75% symbol width on a rounded container.', 'الرمز هو الأيقونة. عاجي دافئ وموكا ثنائي الدرجة وعرض الرمز 75% على حاوية مستديرة.'),
    iconStatus: l('Production candidate. Proposed, requires final approval.', 'مرشح للإنتاج. مقترح ويتطلب الاعتماد النهائي.'),
    iconSizes: l('From 256 down to 16 px', 'من 256 إلى 16 px'),
    splashTitle: l('Launch', 'الإطلاق'),
    splashLead: l('A symbol-first, minimal launch screen. It exists to establish identity briefly before the product. It is never onboarding or marketing.', 'شاشة إطلاق مينيمالية يتصدرها الرمز. تثبّت الهوية لحظة قبل المنتج، وليست تعريفاً أو تسويقاً.'),
    splashStatus: l('Production direction, requires final review.', 'اتجاه إنتاجي يتطلب المراجعة النهائية.'),
    studiesTitle: l('Around the product', 'حول المنتج'),
    studiesLead: l('Illustrative studies composed from the approved assets. They are not official AQARATI templates.', 'دراسات توضيحية مركّبة من الأصول المعتمدة. وليست قوالب رسمية لعقاراتي.'),
    studiesNote: l('Illustrative · composed from approved assets', 'توضيحي · مركّب من أصول معتمدة'),
    web: l('Web header', 'ترويسة الموقع'),
    document: l('Letterhead', 'ورقة المراسلات'),
    social: l('Social profile', 'الملف على وسائل التواصل'),
    docTitle: l('Viewing confirmation', 'تأكيد المعاينة'),
    docBody: l('Your viewing request for 4-Bedroom Contemporary Villa, Al Mouj, Muscat, has been recorded. Availability is confirmed separately.', 'تم تسجيل طلب معاينة فيلا عصرية من 4 غرف، الموج، مسقط. يتم تأكيد التوفر بشكل منفصل.'),
    docMeta: l('Sample document', 'مستند تجريبي'),
    socialLine: l('Trusted by design. Defined by place.', 'موثوقة بالتصميم. محددة بالمكان.'),
    webNav: [l('Buy', 'شراء'), l('Rent', 'إيجار'), l('Professionals', 'المهنيون'), l('Development', 'التطوير')],
  },

  usage: {
    num: '11',
    title: l('Brand usage', 'استخدام العلامة'),
    lead: l('Ten connected standards. The master identity, applied consistently across every touchpoint.', 'عشرة معايير مترابطة. الهوية الرئيسية مطبقة بثبات في كل نقطة تواصل.'),
    topicLabel: l('Topic', 'الموضوع'),
    rulesTitle: l('Master rules', 'القواعد الرئيسية'),
    rulesLead: l('Fourteen rules that protect the clarity, warmth and premium character of the system.', 'أربع عشرة قاعدة تحمي وضوح المنظومة ودفأها وطابعها الراقي.'),
    openSlice: l('Open', 'افتح'),
  },

  final: {
    line1: l('Trusted by design.', 'موثوقة بالتصميم.'),
    line2: l('Defined by place.', 'محددة بالمكان.'),
    closing: l('Quietly distinctive. Consistently trusted.', 'متميزة بهدوء. موثوقة باستمرار.'),
  },

  reveal: {
    title: l('Logo in motion', 'الشعار في حركة'),
    line: l('A house, a wave, a name.', 'بيت وموجة واسم.'),
    body: l('The mark builds itself the way it is constructed: the roofline, the wave, the Arabic and Latin wordmarks, then the line.', 'يتشكل الشعار كما بُني: خط السقف ثم الموجة ثم الكلمتان العربية واللاتينية ثم العبارة.'),
    play: l('Play', 'تشغيل'),
    pause: l('Pause', 'إيقاف'),
    alt: l('AQARATI logo reveal animation', 'عرض متحرك لظهور شعار عقاراتي'),
    note: l('A motion study. The approved vector master on the Identity page stays the source of truth.', 'دراسة حركة. يبقى الملف المتجهي المعتمد في صفحة الهوية هو المرجع.'),
  },

  index: {
    title: l('The chapters', 'الفصول'),
    lead: l('Seven chapters, one identity. Choose where to begin.', 'سبعة فصول وهوية واحدة. اختر من أين تبدأ.'),
    next: l('Next chapter', 'الفصل التالي'),
    back: l('Back to the start', 'العودة إلى البداية'),
    open: l('Open chapter', 'افتح الفصل'),
  },

  footer: {
    rights: l('© AQARATI', '© عقاراتي'),
    note: l('A brand experience built from the approved Figma Brand Foundation.', 'تجربة هوية مبنية من أساس العلامة المعتمد في Figma.'),
  },
} as const;
